packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  esbuild: true
  prisma: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "@scarf/scarf"
  - "unrs-resolver"
