packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  esbuild: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "@scarf/scarf"
  - "unrs-resolver"
